#!/usr/bin/env ruby
#^syntax detection

# this is used for general cookbooks that don't have git repos clearly defined
site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# if fix's are required, fork from https://github.com/opscode/cookbooks,
# fix, and use that repo url in the package definition
# be nice, and submit a pull request!

cookbook 'build-essential',     '>= 1.2.0'
cookbook 'git',                 '>= 2.0.0'
cookbook 'iptables',            '>= 0.10.0'
cookbook 'oh-my-zsh',           :ref => 'master',   :git => 'https://github.com/streamlinesocial/chef-oh-my-zsh.git'
cookbook 'openssl',             '>= 1.0.0'
cookbook 'user',                '>= 0.3.0'
cookbook 'selinux',             '>= 0.5.2'
cookbook 'sls_utils',           :ref => 'master',   :git => 'https://github.com/streamlinesocial/cookbook-sls_utils'
cookbook 'sudo',                :ref => 'master',   :git => 'https://github.com/streamlinesocial/sudo.git'
cookbook 'yum',                 '= 1.0.0' # yum 2.0.x gives problems with ius repo
cookbook 'zsh',                 '>= 1.0.0'

# lamp stack
cookbook 'apache2',             '>= 1.3.2'
cookbook 'mysql',               :ref => 'master',   :git => 'https://github.com/streamlinesocial/mysql.git'
cookbook 'php',                 :ref => 'master',   :git => 'https://github.com/streamlinesocial/php.git'

# app specific
# cookbook 'application',         :ref => '1.0.4',    :git => 'https://github.com/opscode-cookbooks/application.git'
# cookbook 'application_php',     :ref => '1.0.4',    :git => 'https://github.com/opscode-cookbooks/application_php.git'

# symfony apps
# cookbook 'composer',            :ref => 'master',   :git => 'https://github.com/streamlinesocial/chef-composer.git'
# cookbook 'symfony2',            :ref => 'master',   :git => 'https://github.com/streamlinesocial/cookbook-symfony2.git'

# drupal apps
# cookbook 'drush',             :ref => 'master',   :git => 'https://github.com/msonnabaum/chef-drush.git'
